import { describe, expect, it } from 'vitest';

import { OpcZipError, type ZipErrorCode } from './errors.js';
import { DEFAULT_OPC_LIMITS } from './limits.js';
import { buildPackage, buildRawZip, makeEntry, toBytes } from './testing/zip-fixtures.js';
import {
  createBudget,
  crc32,
  deflateForEntry,
  decompressEntry,
  METHOD_DEFLATE,
  METHOD_STORE,
  readZip,
  writeZip,
} from './zip.js';

const utf8 = new TextEncoder();

function expectZipCode(code: ZipErrorCode, run: () => unknown): void {
  try {
    run();
  } catch (error) {
    expect(error).toBeInstanceOf(OpcZipError);
    expect((error as OpcZipError).code).toBe(code);
    return;
  }
  throw new Error(`expected an OpcZipError with code ${code}, but nothing threw`);
}

describe('ZIP reader and writer', () => {
  describe('well-formed archive read and write', () => {
    it('reads and writes well-formed archive with STORE and DEFLATE entries', () => {
      const items = [
        {
          name: '[Content_Types].xml',
          data: '<Types><Default Extension="xml" ContentType="text/xml"/></Types>',
        },
        { name: 'word/document.xml', data: '<w:document><w:body><w:p/></w:body></w:document>' },
        {
          name: 'word/media/image.png',
          data: new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a]),
          store: true,
        },
      ];

      const zipBytes = buildPackage(items);
      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);

      expect(archive.entries.length).toBe(3);
      expect(archive.entries[0]?.name).toBe('[Content_Types].xml');
      expect(archive.entries[0]?.partName).toBeUndefined(); // [Content_Types].xml is not a part
      expect(archive.entries[1]?.name).toBe('word/document.xml');
      expect(archive.entries[1]?.partName).toBe('/word/document.xml');
      expect(archive.entries[1]?.method).toBe(METHOD_DEFLATE);
      expect(archive.entries[2]?.name).toBe('word/media/image.png');
      expect(archive.entries[2]?.partName).toBe('/word/media/image.png');
      expect(archive.entries[2]?.method).toBe(METHOD_STORE);

      // Decompress entries
      const budget = createBudget();
      const ctData = decompressEntry(archive.entries[0]!, DEFAULT_OPC_LIMITS, budget);
      expect(new TextDecoder().decode(ctData)).toBe(items[0]!.data);

      const docData = decompressEntry(archive.entries[1]!, DEFAULT_OPC_LIMITS, budget);
      expect(new TextDecoder().decode(docData)).toBe(items[1]!.data);

      const imgData = decompressEntry(archive.entries[2]!, DEFAULT_OPC_LIMITS, budget);
      expect(imgData).toEqual(items[2]!.data);

      // Write back out and read again
      const savedBytes = writeZip(archive.entries, archive.comment);
      const reArchive = readZip(savedBytes, DEFAULT_OPC_LIMITS);

      expect(reArchive.entries.length).toBe(3);
      expect(reArchive.entries[1]?.name).toBe('word/document.xml');
      const reDocData = decompressEntry(reArchive.entries[1]!, DEFAULT_OPC_LIMITS, createBudget());
      expect(new TextDecoder().decode(reDocData)).toBe(items[1]!.data);
    });
  });

  describe('EOCD locator with and without ZIP comment', () => {
    it('reads an archive without an archive comment', () => {
      const zipBytes = buildRawZip([
        { nameBytes: utf8.encode('word/doc.xml'), data: utf8.encode('<root/>') },
      ]);
      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      expect(archive.comment.length).toBe(0);
      expect(archive.entries.length).toBe(1);
    });

    it('reads an archive with a non-empty archive comment', () => {
      const commentText = 'Generated by OOXML Editor Test Suite';
      const zipBytes = buildRawZip(
        [{ nameBytes: utf8.encode('word/doc.xml'), data: utf8.encode('<root/>') }],
        { comment: utf8.encode(commentText) },
      );
      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      expect(new TextDecoder().decode(archive.comment)).toBe(commentText);
    });

    it('handles backward scanning when archive comment contains EOCD signature bytes', () => {
      // Create a comment that contains the EOCD magic bytes PK\x05\x06 (0x06054b50)
      const trickyComment = new Uint8Array([
        0x50, 0x4b, 0x05, 0x06, 0x00, 0x00, 0x00, 0x00, 0x41, 0x42, 0x43,
      ]);
      const zipBytes = buildRawZip(
        [{ nameBytes: utf8.encode('word/doc.xml'), data: utf8.encode('<root/>') }],
        { comment: trickyComment },
      );
      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      expect(archive.comment).toEqual(trickyComment);
      expect(archive.entries.length).toBe(1);
    });

    it('fails with eocd-not-found when input is not a ZIP', () => {
      const garbage = new Uint8Array(100);
      garbage.fill(0xaa);
      expectZipCode('eocd-not-found', () => readZip(garbage, DEFAULT_OPC_LIMITS));
    });
  });

  describe('Central Directory vs local header disagreement (Central Directory is authoritative)', () => {
    it('uses Central Directory for CRC, sizes, and metadata while using local header offsets/lengths to locate payload', () => {
      const payload = utf8.encode('<w:document><w:body>Secret text</w:body></w:document>');
      const realCrc = crc32(payload);

      // Local header extra is 10 bytes, Central Directory extra is 0 bytes.
      // This creates a discrepancy between local and central header structures.
      const localExtra = new Uint8Array(10);
      localExtra.fill(0x42);

      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data: payload,
          localExtra,
          // Local header will have extraLength = 10; Central Directory will have extraLength = 0
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      const entry = archive.entries[0]!;

      expect(entry.crc32).toBe(realCrc);
      expect(entry.uncompressedSize).toBe(payload.length);
      // Local header extra was read and stripped of ZIP64
      expect(entry.localExtra).toEqual(localExtra);
      expect(entry.centralExtra.length).toBe(0);

      // Verify decompressEntry accurately locates the payload despite localExtra padding
      const budget = createBudget();
      const extracted = decompressEntry(entry, DEFAULT_OPC_LIMITS, budget);
      expect(extracted).toEqual(payload);
    });

    it('rejects decompression if central directory uncompressed size disagrees with inflated byte count', () => {
      const payload = utf8.encode('Exact content');
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data: payload,
          uncompressedSizeOverride: payload.length + 10, // Central directory claims 10 extra bytes
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      const entry = archive.entries[0]!;

      expectZipCode('truncated', () => decompressEntry(entry, DEFAULT_OPC_LIMITS, createBudget()));
    });
  });

  describe('STORED vs DEFLATE methods', () => {
    it('supports STORED method', () => {
      const data = utf8.encode('Uncompressed plain data');
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/media/image.png'),
          data,
          method: METHOD_STORE,
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      expect(archive.entries[0]?.method).toBe(METHOD_STORE);

      const budget = createBudget();
      const extracted = decompressEntry(archive.entries[0]!, DEFAULT_OPC_LIMITS, budget);
      expect(extracted).toEqual(data);
      expect(budget.totalUncompressedBytes).toBe(data.length);
    });

    it('supports DEFLATE method', () => {
      const data = utf8.encode('Repetitive compressible data '.repeat(50));
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data,
          method: METHOD_DEFLATE,
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      expect(archive.entries[0]?.method).toBe(METHOD_DEFLATE);

      const budget = createBudget();
      const extracted = decompressEntry(archive.entries[0]!, DEFAULT_OPC_LIMITS, budget);
      expect(extracted).toEqual(data);
      expect(budget.totalUncompressedBytes).toBe(data.length);
    });

    it('rejects unsupported compression methods', () => {
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data: utf8.encode('test'),
          method: 14, // LZMA or BZIP2 or other unsupported method
        },
      ]);

      expectZipCode('unsupported-method', () => readZip(zipBytes, DEFAULT_OPC_LIMITS));
    });

    it('deflateForEntry chooses DEFLATE for compressible content and STORE for incompressible', () => {
      // Highly compressible
      const compressible = utf8.encode('test string '.repeat(100));
      const compressedRes = deflateForEntry(compressible);
      expect(compressedRes.method).toBe(METHOD_DEFLATE);
      expect(compressedRes.data.length).toBeLessThan(compressible.length);

      // Incompressible (very short or random)
      const incompressible = new Uint8Array([0x12, 0x34, 0x56]);
      const storedRes = deflateForEntry(incompressible);
      expect(storedRes.method).toBe(METHOD_STORE);
      expect(storedRes.data).toEqual(incompressible);
    });
  });

  describe('data descriptors', () => {
    it('reads an archive produced with data descriptors (bit 3 set, zero sizes in local header, trailer after data)', () => {
      const data = utf8.encode(
        '<w:document><w:p><w:r><w:t>Streaming producer</w:t></w:r></w:p></w:document>',
      );
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data,
          method: METHOD_DEFLATE,
          dataDescriptor: true,
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      const entry = archive.entries[0]!;
      // Entry flags as read has bit 3 set
      expect((entry.flags & (1 << 3)) !== 0).toBe(true);
      expect(entry.uncompressedSize).toBe(data.length);

      const extracted = decompressEntry(entry, DEFAULT_OPC_LIMITS, createBudget());
      expect(extracted).toEqual(data);

      // writeZip clears bit 3 and normalizes by omitting data descriptors
      const reWritten = writeZip(archive.entries);
      const reArchive = readZip(reWritten, DEFAULT_OPC_LIMITS);
      expect((reArchive.entries[0]!.flags & (1 << 3)) !== 0).toBe(false);
      const reExtracted = decompressEntry(
        reArchive.entries[0]!,
        DEFAULT_OPC_LIMITS,
        createBudget(),
      );
      expect(reExtracted).toEqual(data);
    });
  });

  describe('ZIP64 extra fields', () => {
    it('reads entries with ZIP64 sizes extra fields', () => {
      const data = utf8.encode('ZIP64 sizes entry');
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data,
          zip64: { sizes: true },
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      const entry = archive.entries[0]!;
      expect(entry.uncompressedSize).toBe(data.length);
      expect(entry.compressedSize).toBe(data.length);

      const extracted = decompressEntry(entry, DEFAULT_OPC_LIMITS, createBudget());
      expect(extracted).toEqual(data);
    });

    it('reads entries with ZIP64 offset extra fields', () => {
      const data = utf8.encode('ZIP64 offset entry');
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data,
          zip64: { offset: true },
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      const entry = archive.entries[0]!;
      expect(entry.uncompressedSize).toBe(data.length);

      const extracted = decompressEntry(entry, DEFAULT_OPC_LIMITS, createBudget());
      expect(extracted).toEqual(data);
    });

    it('reads entries with both ZIP64 sizes and offset', () => {
      const data = utf8.encode('ZIP64 both sizes and offset');
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data,
          zip64: { sizes: true, offset: true },
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      const entry = archive.entries[0]!;

      const extracted = decompressEntry(entry, DEFAULT_OPC_LIMITS, createBudget());
      expect(extracted).toEqual(data);
    });

    it('throws zip64-invalid if base field is saturated but ZIP64 extra field is absent', () => {
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data: utf8.encode('data'),
          zip64: { sizes: true },
          omitZip64Extra: true,
        },
      ]);

      expectZipCode('zip64-invalid', () => readZip(zipBytes, DEFAULT_OPC_LIMITS));
    });
  });

  describe('error handling: corrupted CRC32, truncation mid-entry, duplicate entry names', () => {
    it('detects corrupted CRC32 during decompression', () => {
      const data = utf8.encode('Legitimate content');
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data,
          crcOverride: 0x12345678, // Corrupt CRC
        },
      ]);

      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);
      expectZipCode('crc-mismatch', () =>
        decompressEntry(archive.entries[0]!, DEFAULT_OPC_LIMITS, createBudget()),
      );
    });

    it('detects truncation mid-entry when entry data extends past end of archive', () => {
      const data = utf8.encode('Short content');
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data,
          compressedSizeOverride: data.length + 500, // Central directory claims 500 extra bytes
        },
      ]);

      expectZipCode('truncated', () => readZip(zipBytes, DEFAULT_OPC_LIMITS));
    });

    it('detects duplicate entry names that map to the same part name', () => {
      const zipBytes = buildRawZip([
        {
          nameBytes: utf8.encode('word/document.xml'),
          data: utf8.encode('First copy'),
        },
        {
          nameBytes: utf8.encode('WORD/DOCUMENT.XML'), // Case-insensitively identical part name
          data: utf8.encode('Second copy'),
        },
      ]);

      expectZipCode('duplicate-entry', () => readZip(zipBytes, DEFAULT_OPC_LIMITS));
    });
  });

  describe('entry-order preservation across open -> save', () => {
    it('preserves exact entry order across read and write', () => {
      const names = [
        'customXml/item1.xml',
        'word/document.xml',
        '[Content_Types].xml',
        '_rels/.rels',
        'word/styles.xml',
        'docProps/app.xml',
      ];

      const items = names.map((name) => ({
        name,
        data: `<content name="${name}"/>`,
      }));

      const zipBytes = buildPackage(items);
      const archive = readZip(zipBytes, DEFAULT_OPC_LIMITS);

      expect(archive.entries.map((e) => e.name)).toEqual(names);

      const savedBytes = writeZip(archive.entries, archive.comment);
      const reArchive = readZip(savedBytes, DEFAULT_OPC_LIMITS);

      expect(reArchive.entries.map((e) => e.name)).toEqual(names);
    });
  });
});
