import { describe, expect, it } from 'vitest';
import type {
  IrComplexType,
  IrParticle,
  IrSchemaSet,
  IrSimpleType,
  Occurs,
  QName,
  SourceRef,
  TypeRef,
} from '../ir.js';
import { qnameKey } from '../ir.js';
import { normalize } from '../normalize.js';
import { emitReader } from './reader.js';

const SRC: SourceRef = { file: 'transitional/wml.xsd', line: 42 };
const q = (name: string, ns = 'wml'): QName => ({ ns, name });
const ref = (name: string, ns = 'wml'): TypeRef => ({ kind: 'named', ref: q(name, ns) });
const str: TypeRef = { kind: 'builtin', name: 'xsd:string' };

const el = (name: string, type: TypeRef, min = 1, max: Occurs = 1): IrParticle => ({
  kind: 'element',
  name,
  ns: 'wml',
  type,
  min,
  max,
  source: SRC,
});
const seq = (items: IrParticle[], min = 1, max: Occurs = 1): IrParticle => ({
  kind: 'sequence',
  items,
  min,
  max,
  source: SRC,
});
const choice = (items: IrParticle[], min = 1, max: Occurs = 1): IrParticle => ({
  kind: 'choice',
  items,
  min,
  max,
  source: SRC,
});

function schema(parts: {
  complexTypes?: IrComplexType[];
  simpleTypes?: IrSimpleType[];
}): IrSchemaSet {
  const byKey = <T extends { name: QName }>(xs: readonly T[] = []): ReadonlyMap<string, T> =>
    new Map(xs.map((x) => [qnameKey(x.name), x]));
  return {
    namespaces: new Map(),
    uriToToken: new Map(),
    complexTypes: byKey(parts.complexTypes),
    simpleTypes: byKey(parts.simpleTypes),
    globalElements: new Map(),
    groups: new Map(),
    attributeGroups: new Map(),
    diagnostics: [],
  };
}

const empty = (name: string): IrComplexType => ({
  kind: 'complexType',
  name: q(name),
  content: { kind: 'empty' },
  attributes: [],
  dialects: ['transitional'],
  source: SRC,
});

const emit = (ir: IrSchemaSet): string => emitReader(normalize(ir), 'wml').contents;

describe('reader emitter', () => {
  it('emits simple parsers, attribute diagnostics, ordered choices, and raw preservation', () => {
    const out = emit(
      schema({
        simpleTypes: [
          {
            kind: 'enum',
            name: q('ST_Jc'),
            base: str,
            values: [
              { value: 'start', source: SRC },
              { value: 'center', source: SRC },
            ],
            dialects: ['transitional'],
            source: SRC,
          },
        ],
        complexTypes: [
          {
            kind: 'complexType',
            name: q('CT_Host'),
            content: {
              kind: 'elements',
              particle: seq([
                el('r', ref('CT_R'), 0, 'unbounded'),
                choice([el('a', ref('CT_A')), el('b', ref('CT_B'))], 0, 'unbounded'),
              ]),
            },
            attributes: [
              {
                kind: 'attribute',
                name: 'val',
                ns: null,
                type: ref('ST_Jc'),
                use: 'required',
                source: SRC,
              },
            ],
            dialects: ['transitional'],
            source: SRC,
          },
          empty('CT_R'),
          empty('CT_A'),
          empty('CT_B'),
        ],
      }),
    );

    expect(out).toMatchInlineSnapshot(`
      "/**
       * @generated by @ooxml/codegen — do not edit.
       *
       * Source: readers for the wml namespace of the ECMA-376 5th edition schema set
       *
       * Regenerate with \`pnpm gen\`. CI fails if this file differs from a fresh run,
       * so hand edits will be reverted by the next build.
       */

      import {
        type ReadContext,
        type XmlAttr,
        type XmlCursor,
        collapse,
        isIgnorableWhitespace,
        requireStart,
      } from '../../runtime/index.js';
      import {
        type CT_A,
        type CT_B,
        type CT_Host,
        type CT_Host_Content,
        type CT_R,
        type ST_Jc,
        ST_Jc_VALUES,
      } from './types.js';

      // Simple-type parsers. \`undefined\` means "outside the lexical space".

      export function parseST_Jc(value: string): ST_Jc | undefined {
        const s = collapse(value);
        return ST_Jc_VALUES.has(s) ? (s as ST_Jc) : undefined;
      }

      // Complex-type readers.

      /** Read a \`CT_A\`. See \`transitional/wml.xsd:42\`. */
      export function readCT_A(cur: XmlCursor, ctx: ReadContext): CT_A {
        const start = requireStart(cur, 'CT_A');
        let $unknownAttrs: XmlAttr[] | undefined;

        for (const a of start.attrs) {
          ctx.unexpectedAttribute('CT_A', a, cur);
          ($unknownAttrs ??= []).push(a);
        }

        cur.next();
        for (;;) {
          const ev = cur.current;
          if (ev === undefined) { ctx.unexpectedEof('CT_A', cur); break; }
          if (ev.type === 'endElement') { cur.next(); break; }
          if (ev.type === 'startElement') {
            ctx.unexpectedElement('CT_A', ev.localName, ev.uri, cur);
            cur.skip();
            continue;
          }
          if (ev.type === 'text' && !isIgnorableWhitespace(ev.value)) ctx.unexpectedText('CT_A', cur);
          cur.next();
        }
        return {
          $unknownAttrs,
        };
      }

      /** Read a \`CT_B\`. See \`transitional/wml.xsd:42\`. */
      export function readCT_B(cur: XmlCursor, ctx: ReadContext): CT_B {
        const start = requireStart(cur, 'CT_B');
        let $unknownAttrs: XmlAttr[] | undefined;

        for (const a of start.attrs) {
          ctx.unexpectedAttribute('CT_B', a, cur);
          ($unknownAttrs ??= []).push(a);
        }

        cur.next();
        for (;;) {
          const ev = cur.current;
          if (ev === undefined) { ctx.unexpectedEof('CT_B', cur); break; }
          if (ev.type === 'endElement') { cur.next(); break; }
          if (ev.type === 'startElement') {
            ctx.unexpectedElement('CT_B', ev.localName, ev.uri, cur);
            cur.skip();
            continue;
          }
          if (ev.type === 'text' && !isIgnorableWhitespace(ev.value)) ctx.unexpectedText('CT_B', cur);
          cur.next();
        }
        return {
          $unknownAttrs,
        };
      }

      /** Read a \`CT_Host\`. See \`transitional/wml.xsd:42\`. */
      export function readCT_Host(cur: XmlCursor, ctx: ReadContext): CT_Host {
        const start = requireStart(cur, 'CT_Host');
        let val: ST_Jc | undefined;
        let $unknownAttrs: XmlAttr[] | undefined;

        for (const a of start.attrs) {
          if (a.uri === '') {
            switch (a.localName) {
              case 'val': {
                const v = parseST_Jc(a.value);
                if (v !== undefined) {
                  val = v;
                  continue;
                }
                ctx.invalidValue('CT_Host', a, 'ST_Jc', cur);
                break;
              }
            }
          }
          ctx.unexpectedAttribute('CT_Host', a, cur);
          ($unknownAttrs ??= []).push(a);
        }

        if (val === undefined) ctx.missingRequired('CT_Host', 'val', cur);

        const r: CT_R[] = [];
        const content: CT_Host_Content[] = [];

        const NS_wml = ctx.uris['wml'];
        cur.next();
        for (;;) {
          const ev = cur.current;
          if (ev === undefined) { ctx.unexpectedEof('CT_Host', cur); break; }
          if (ev.type === 'endElement') { cur.next(); break; }
          if (ev.type === 'startElement') {
            if (ev.uri === NS_wml) {
              switch (ev.localName) {
                case 'r': {
                  r.push(readCT_R(cur, ctx));
                  continue;
                }
                case 'a': {
                  content.push({ kind: 'a', value: readCT_A(cur, ctx) });
                  continue;
                }
                case 'b': {
                  content.push({ kind: 'b', value: readCT_B(cur, ctx) });
                  continue;
                }
              }
            }
            ctx.unexpectedElement('CT_Host', ev.localName, ev.uri, cur);
            content.push({ kind: '$raw', value: cur.skipToRaw() });
            continue;
          }
          if (ev.type === 'text' && !isIgnorableWhitespace(ev.value)) ctx.unexpectedText('CT_Host', cur);
          cur.next();
        }

        return {
          r,
          content,
          val,
          $unknownAttrs,
        };
      }

      /** Read a \`CT_R\`. See \`transitional/wml.xsd:42\`. */
      export function readCT_R(cur: XmlCursor, ctx: ReadContext): CT_R {
        const start = requireStart(cur, 'CT_R');
        let $unknownAttrs: XmlAttr[] | undefined;

        for (const a of start.attrs) {
          ctx.unexpectedAttribute('CT_R', a, cur);
          ($unknownAttrs ??= []).push(a);
        }

        cur.next();
        for (;;) {
          const ev = cur.current;
          if (ev === undefined) { ctx.unexpectedEof('CT_R', cur); break; }
          if (ev.type === 'endElement') { cur.next(); break; }
          if (ev.type === 'startElement') {
            ctx.unexpectedElement('CT_R', ev.localName, ev.uri, cur);
            cur.skip();
            continue;
          }
          if (ev.type === 'text' && !isIgnorableWhitespace(ev.value)) ctx.unexpectedText('CT_R', cur);
          cur.next();
        }
        return {
          $unknownAttrs,
        };
      }
      "
    `);
  });
});
